# Generated by Django 2.2.4 on 2020-06-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('densiteapp', '0002_oilmudcalculation_watermudcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboardTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Downhole Pressure')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Downhole Temperature')),
                ('initial_density', models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Initial Mud Density')),
                ('final_density', models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Final Mud Density')),
                ('type_model', models.CharField(blank=True, max_length=30, verbose_name='Type of Model')),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
